[build]
  command = "node build-netlify.js"
  publish = "dist/public"

[build.environment]
  NODE_VERSION = "20"

# Redirect all requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API endpoint redirects to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200